error_reporting = E_ALL
display_errors = On
display_startup_errors = On
memory_limit = 512M

[xdebug]
xdebug.mode = debug,coverage # Показывает насколько хорошо код покрыт тестами
xdebug.start_with_request = yes
xdebug.client_host = host.docker.internal