services:
  php-starter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-starter
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      DB_HOST: php-db
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - php-network
    depends_on:
      php-db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: php-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-network
    depends_on:
      - php-starter

  php-db:
    image: mysql:8.4
    container_name: php-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3307:3306" # Это нужно что бы доступ к БД был только локально без открытого внешнего доступа
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php-network
    healthcheck: # ждем пока БД не станет
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: php-redis
    restart: always
    command: redis-server --save "" --appendonly no
    networks:
      - php-network

volumes:
  mysql_data:

networks:
  php-network:
    driver: bridge